server:
  port: 8080

spring:
  application:
    name: notes-api
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/notesdb}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
